export const defaultLogo = '/logo.svg';
export const defaultTitle = 'ForkFlow CRM';
export const defaultContactGender = [];
export const defaultCompanySectors = [];
export const defaultDealCategories = [];
export const defaultDealPipelineStatuses = [];
export const defaultDealStages = [];
export const defaultNoteStatuses = [];
export const defaultTaskTypes = [];
